import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import ClientProvider from "@/lib/providers/client-provider";
import { cn } from "@/lib/utils";
import LanguageChanger from "@/app/[locale]/LanguageChanger";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
	params: { locale },
}: {
	children: React.ReactNode;
	params: { locale: string };
}) {
	let messages;
	try {
		messages = (await import(`../../messages/${locale}.json`)).default;
	} catch (error) {
		notFound();
	}
	return (
		<html lang={locale}>
			<body className={cn(inter.className, "relative")}>
				<NextIntlClientProvider messages={messages}>
					<ClientProvider>
						<>
							<header className='p-4'>
								<LanguageChanger locale={locale} />
							</header>
							<main className='flex min-h-screen flex-col items-center justify-between p-8 lg:p-24'>
								{children}
							</main>
						</>
					</ClientProvider>
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
